/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogoforca06;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Guilherme_Prestes
 */
public class TelaJogoNormal extends javax.swing.JFrame {
    
    String PalavraSorteada = new String();
    ArrayList Tentativas = new ArrayList();
    int MaxTentativas = 7 ;
    int NumTentativas = 0 ;
    boolean FimDoJogo = true;
    ImageIcon icon0 = new ImageIcon("01.png");
    ImageIcon icon1 = new ImageIcon("02.png");
    ImageIcon icon2 = new ImageIcon("03.png");
    ImageIcon icon3 = new ImageIcon("04.png");
    ImageIcon icon4 = new ImageIcon("05.png");
    ImageIcon icon5 = new ImageIcon("06.png");
    ImageIcon icon6 = new ImageIcon("07.png");
    ImageIcon icon7 = new ImageIcon("08.png");
    ArrayList PalavrasArquivo = new ArrayList();
    ArrayList DicasArquivo = new ArrayList();
    
    
    

    /**
     * Creates new form TelaJogoFacil
     */
    public TelaJogoNormal() {
        initComponents();
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        voceGanhou = new javax.swing.JDialog();
        btnPARsim = new javax.swing.JButton();
        btnPARnao = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        vocePerdeu = new javax.swing.JDialog();
        btnPERsim = new javax.swing.JButton();
        btnPERnao = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        desejaSair = new javax.swing.JDialog();
        btnSAIRsim = new javax.swing.JButton();
        btnSAIRnao = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        CampoTentar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblDigite = new javax.swing.JLabel();
        TxtDica = new javax.swing.JTextField();
        PalavraForca = new javax.swing.JTextField();
        btnOK = new javax.swing.JButton();
        lblImagem = new javax.swing.JLabel();
        btnNovoJogo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        fundo = new javax.swing.JLabel();

        voceGanhou.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPARsim.setText("SIM");
        btnPARsim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPARsimActionPerformed(evt);
            }
        });
        voceGanhou.getContentPane().add(btnPARsim, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 80, 30));

        btnPARnao.setText("NÃO");
        btnPARnao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPARnaoActionPerformed(evt);
            }
        });
        voceGanhou.getContentPane().add(btnPARnao, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 80, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/parebens.png"))); // NOI18N
        voceGanhou.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        vocePerdeu.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPERsim.setText("SIM");
        btnPERsim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPERsimActionPerformed(evt);
            }
        });
        vocePerdeu.getContentPane().add(btnPERsim, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 70, 30));

        btnPERnao.setText("NÃO");
        btnPERnao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPERnaoActionPerformed(evt);
            }
        });
        vocePerdeu.getContentPane().add(btnPERnao, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 80, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/perdeu.png"))); // NOI18N
        vocePerdeu.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        desejaSair.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSAIRsim.setText("SIM");
        btnSAIRsim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSAIRsimActionPerformed(evt);
            }
        });
        desejaSair.getContentPane().add(btnSAIRsim, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 80, 40));

        btnSAIRnao.setText("NÃO");
        btnSAIRnao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSAIRnaoActionPerformed(evt);
            }
        });
        desejaSair.getContentPane().add(btnSAIRnao, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 80, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/querSair.png"))); // NOI18N
        desejaSair.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CampoTentar.setEnabled(false);
        getContentPane().add(CampoTentar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 50, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Dica:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, -1, -1));

        lblDigite.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDigite.setForeground(new java.awt.Color(255, 255, 255));
        lblDigite.setText("Digite uma Letra:");
        getContentPane().add(lblDigite, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, -1, -1));

        TxtDica.setEditable(false);
        getContentPane().add(TxtDica, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, 340, 30));

        PalavraForca.setEditable(false);
        PalavraForca.setEnabled(false);
        PalavraForca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PalavraForcaActionPerformed(evt);
            }
        });
        getContentPane().add(PalavraForca, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 350, 40));

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });
        getContentPane().add(btnOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, 90, 30));

        lblImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/01.png"))); // NOI18N
        getContentPane().add(lblImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        btnNovoJogo.setText("Novo Jogo");
        btnNovoJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoJogoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNovoJogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, -1, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Normal");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/tela 02.png"))); // NOI18N
        getContentPane().add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PalavraForcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PalavraForcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PalavraForcaActionPerformed

    private void btnPARnaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPARnaoActionPerformed
       System.exit(0);
    }//GEN-LAST:event_btnPARnaoActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        if (!FimDoJogo){
        tentarletra(CampoTentar.getText());
        CampoTentar.setText("");
        }
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnNovoJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoJogoActionPerformed
         lblDigite.enable(true);
        CampoTentar.enable(true);
      
        TxtDica.enable(true);
        PalavraForca.enable(true);
        
        PalavraForca.setText("");
        Tentativas.clear();
        sortearpalavra(); 
        FimDoJogo=false; 
        lblImagem.setIcon(icon0); 
        NumTentativas=0;
        desenharpalavra(false);
    }//GEN-LAST:event_btnNovoJogoActionPerformed

    private void btnPARsimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPARsimActionPerformed
       PalavraForca.setText("");
        Tentativas.clear();
        sortearpalavra();
        FimDoJogo=false;
        lblImagem.setIcon(icon0);
        NumTentativas=0;
        desenharpalavra(false);
        voceGanhou.setVisible(false);
    }//GEN-LAST:event_btnPARsimActionPerformed

    private void btnPERsimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPERsimActionPerformed
        PalavraForca.setText("");
        Tentativas.clear();
        sortearpalavra();
        FimDoJogo=false;
        lblImagem.setIcon(icon0);
        NumTentativas=0;
        desenharpalavra(false);
        vocePerdeu.setVisible(false);
    }//GEN-LAST:event_btnPERsimActionPerformed

    private void btnPERnaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPERnaoActionPerformed
       System.exit(0);
    }//GEN-LAST:event_btnPERnaoActionPerformed

    private void btnSAIRsimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSAIRsimActionPerformed
       System.exit(0);
    }//GEN-LAST:event_btnSAIRsimActionPerformed

    private void btnSAIRnaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSAIRnaoActionPerformed
      desejaSair.setVisible(false);
    }//GEN-LAST:event_btnSAIRnaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaJogoNormal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaJogoNormal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaJogoNormal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaJogoNormal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaJogoNormal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CampoTentar;
    private javax.swing.JTextField PalavraForca;
    private javax.swing.JTextField TxtDica;
    private javax.swing.JButton btnNovoJogo;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnPARnao;
    private javax.swing.JButton btnPARsim;
    private javax.swing.JButton btnPERnao;
    private javax.swing.JButton btnPERsim;
    private javax.swing.JButton btnSAIRnao;
    private javax.swing.JButton btnSAIRsim;
    private javax.swing.JDialog desejaSair;
    private javax.swing.JLabel fundo;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblDigite;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JDialog voceGanhou;
    private javax.swing.JDialog vocePerdeu;
    // End of variables declaration//GEN-END:variables


 public void sortearpalavra() {
       
     
     
     try {
            File Arquivo = new File("Normal.txt"); 
            FileReader leitor = new FileReader(Arquivo);
            BufferedReader leitorBuf = new BufferedReader(leitor);
            PalavrasArquivo.clear(); 
            DicasArquivo.clear(); 

            String linha=null;

            while((linha = leitorBuf.readLine()) !=null){
                String colunas[] = linha.split("#");
                PalavrasArquivo.add(colunas[0]);
                DicasArquivo.add(colunas[1]);
            }

            leitorBuf.close();

            int TotalPalavras = PalavrasArquivo.size();
            int CodPalavraSorteada = (int) (Math.random()*(TotalPalavras)) ;
            PalavraSorteada = (String) PalavrasArquivo.get(CodPalavraSorteada);
            PalavraSorteada= PalavraSorteada.toUpperCase();
            TxtDica.setText("DICA: "+(String) DicasArquivo.get(CodPalavraSorteada));
        }
        catch(Exception ex) {
            System.out.println("Erro: "+ ex.toString());};
    }

  public void desenharpalavra(boolean MostrarTodaAPalavra){
        String tempTexto = new String();
        boolean faltauma = false;
        for(int n=1;n<=PalavraSorteada.length();n++){
            if((MostrarTodaAPalavra) || (Tentativas.contains(PalavraSorteada.substring(n-1, n)))){
                tempTexto=tempTexto+PalavraSorteada.substring(n-1, n);
            }else{
                tempTexto=tempTexto+"_";
                faltauma=true;
            }
            tempTexto=tempTexto+" ";
        }

        PalavraForca.setText(tempTexto);

        if(!faltauma){
            FimDoJogo=true;
                if ((NumTentativas)<7){
                    voceGanhou.pack();
                    voceGanhou.setLocationRelativeTo(null);
                    voceGanhou.setVisible(true);
                }
            
            // Dá pra mostrar uma outra mensagem aqui.
        }
        
  }
        
    
    public void tentarletra(String Letra){
        Letra= Letra.toUpperCase();
        if(Tentativas.contains(Letra)){
            // Mostrar mensagem de que já foi tentada esta letra
        }else{ 
            // Armazena a letra nova na lista de tentativas.
            Tentativas.add(Letra);
            if(PalavraSorteada.contains(Letra)){
                // Acertou
                desenharpalavra(false);
            }else{
                NumTentativas=NumTentativas+1;//vai adicionando o numero de tentativas; se errar, adiciona o desenho
                switch(NumTentativas){
                    case(1):{
                        lblImagem.setIcon(icon1);
                        break;
                    }
                    case(2):{
                        lblImagem.setIcon(icon2);
                        break;
                    }
                    case(3):{
                        lblImagem.setIcon(icon3);
                        break;
                    }
                    case(4):{
                        lblImagem.setIcon(icon4);
                        break;
                    }
                    case(5):{
                        lblImagem.setIcon(icon5);
                        break;
                    }
                    
                    case(6):{
                        lblImagem.setIcon(icon5);
                        break;
                    }
                    case(7):{
                        lblImagem.setIcon(icon6);
                        break;
                    }
                    case(8):{
                        lblImagem.setIcon(icon7);
                        FimDoJogo=true;
                        desenharpalavra(true);
                        FimDoJogo=true;
                        vocePerdeu.pack();
                        vocePerdeu.setLocationRelativeTo(null);
                        vocePerdeu.setVisible(true);
                        break;
                    }
                }
            }
        }
    }
        
}







